/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardCopyTradingRouteImport } from './routes/dashboard/copy-trading'
import { Route as AdminTraderManagerRouteImport } from './routes/admin/trader-manager'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as AdminKycReviewRouteImport } from './routes/admin/kyc-review'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCopyTradingRoute = DashboardCopyTradingRouteImport.update({
  id: '/copy-trading',
  path: '/copy-trading',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminTraderManagerRoute = AdminTraderManagerRouteImport.update({
  id: '/admin/trader-manager',
  path: '/admin/trader-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKycReviewRoute = AdminKycReviewRouteImport.update({
  id: '/admin/kyc-review',
  path: '/admin/kyc-review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/settings': typeof SettingsRoute
  '/kyc': typeof KycRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/trader-manager': typeof AdminTraderManagerRoute
  '/admin/kyc-review': typeof AdminKycReviewRoute
  '/dashboard/copy-trading': typeof DashboardCopyTradingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/settings': typeof SettingsRoute
  '/kyc': typeof KycRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/trader-manager': typeof AdminTraderManagerRoute
  '/admin/kyc-review': typeof AdminKycReviewRoute
  '/dashboard/copy-trading': typeof DashboardCopyTradingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/settings': typeof SettingsRoute
  '/kyc': typeof KycRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/trader-manager': typeof AdminTraderManagerRoute
  '/admin/kyc-review': typeof AdminKycReviewRoute
  '/dashboard/copy-trading': typeof DashboardCopyTradingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/signup'
    | '/settings'
    | '/kyc'
    | '/admin/dashboard'
    | '/admin/trader-manager'
    | '/admin/kyc-review'
    | '/dashboard/copy-trading'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/signup'
    | '/settings'
    | '/kyc'
    | '/admin/dashboard'
    | '/admin/trader-manager'
    | '/admin/kyc-review'
    | '/dashboard/copy-trading'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/signup'
    | '/settings'
    | '/kyc'
    | '/admin/dashboard'
    | '/admin/trader-manager'
    | '/admin/kyc-review'
    | '/dashboard/copy-trading'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SettingsRoute: typeof SettingsRoute
  KycRoute: typeof KycRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminTraderManagerRoute: typeof AdminTraderManagerRoute
  AdminKycReviewRoute: typeof AdminKycReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/copy-trading': {
      id: '/dashboard/copy-trading'
      path: '/copy-trading'
      fullPath: '/dashboard/copy-trading'
      preLoaderRoute: typeof DashboardCopyTradingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/trader-manager': {
      id: '/admin/trader-manager'
      path: '/admin/trader-manager'
      fullPath: '/admin/trader-manager'
      preLoaderRoute: typeof AdminTraderManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kyc-review': {
      id: '/admin/kyc-review'
      path: '/admin/kyc-review'
      fullPath: '/admin/kyc-review'
      preLoaderRoute: typeof AdminKycReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardCopyTradingRoute: typeof DashboardCopyTradingRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCopyTradingRoute: DashboardCopyTradingRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DashboardRoute: DashboardRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SettingsRoute: SettingsRoute,
  KycRoute: KycRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminTraderManagerRoute: AdminTraderManagerRoute,
  AdminKycReviewRoute: AdminKycReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()